use rand::Rng;
use rand::seq::SliceRandom;

const LEFT: &[&str] = &[
    "admiring",
    "adoring",
    "affectionate",
    "agitated",
    "amazing",
    "angry",
    "asymmetric",
    "awesome",
    "beautiful",
    "blissful",
    "bold",
    "boring",
    "brave",
    "busy",
    "charming",
    "clever",
    "cool",
    "compassionate",
    "competent",
    "concurrent",
    "condescending",
    "confident",
    "cranky",
    "crazy",
    "cybernetic",
    "dazzling",
    "determined",
    "deterministic",
    "distracted",
    "dreamy",
    "eager",
    "ecstatic",
    "elastic",
    "elated",
    "elegant",
    "eloquent",
    "epic",
    "exciting",
    "fervent",
    "festive",
    "flamboyant",
    "focused",
    "friendly",
    "frosty",
    "funny",
    "gallant",
    "gifted",
    "goofy",
    "gracious",
    "great",
    "happy",
    "hardcore",
    "heuristic",
    "hopeful",
    "hungry",
    "immutable",
    "infallible",
    "inspiring",
    "intelligent",
    "interesting",
    "jolly",
    "jovial",
    "keen",
    "kind",
    "laughing",
    "loving",
    "lucid",
    "magical",
    "mystifying",
    "modest",
    "musing",
    "naughty",
    "nervous",
    "neural",
    "nice",
    "nifty",
    "nostalgic",
    "objective",
    "optimistic",
    "peaceful",
    "pedantic",
    "pensive",
    "practical",
    "priceless",
    "quantum",
    "quirky",
    "quizzical",
    "recursing",
    "recursive",
    "relaxed",
    "reverent",
    "romantic",
    "sad",
    "serene",
    "sharp",
    "silly",
    "sleepy",
    "stoic",
    "strange",
    "stupefied",
    "suspicious",
    "sweet",
    "tender",
    "thirsty",
    "trusting",
    "unruffled",
    "upbeat",
    "vibrant",
    "vigilant",
    "vigorous",
    "wizardly",
    "wonderful",
    "xenodochial",
    "youthful",
    "zealous",
    "zen",
];

const RIGHT: &[&str] = &[
    "agnesi",
    "albattani",
    "allen",
    "almeida",
    "antonelli",
    "archimedes",
    "ardinghelli",
    "aryabhata",
    "austin",
    "babbage",
    "banach",
    "banzai",
    "bardeen",
    "bartik",
    "bassi",
    "beaver",
    "bell",
    "bengio",
    "benz",
    "bernerslee",
    "bhabha",
    "bhaskara",
    "black",
    "blackburn",
    "blackwell",
    "bohr",
    "booth",
    "borg",
    "bose",
    "bouman",
    "boyd",
    "brahmagupta",
    "brattain",
    "brown",
    "buck",
    "burnell",
    "cannon",
    "carson",
    "cartwright",
    "carver",
    "cerf",
    "chandrasekhar",
    "chaplygin",
    "chatelet",
    "chatterjee",
    "chaum",
    "chebyshev",
    "clarke",
    "cohen",
    "colden",
    "cori",
    "cray",
    "curran",
    "curie",
    "darwin",
    "davinci",
    "dewdney",
    "dhawan",
    "diffie",
    "dijkstra",
    "dirac",
    "driscoll",
    "dubinsky",
    "easley",
    "edison",
    "einstein",
    "elbakyan",
    "elgamal",
    "elion",
    "ellis",
    "engelbart",
    "euclid",
    "euler",
    "faraday",
    "feistel",
    "fermat",
    "fermi",
    "feynman",
    "franklin",
    "gagarin",
    "galileo",
    "galois",
    "ganguly",
    "gates",
    "gauss",
    "germain",
    "goldberg",
    "goldstine",
    "goldwasser",
    "golick",
    "goodall",
    "gould",
    "greider",
    "grothendieck",
    "haibt",
    "hamilton",
    "haslett",
    "hassabis",
    "hawking",
    "hellman",
    "heisenberg",
    "hermann",
    "herschel",
    "hertz",
    "heyrovsky",
    "hinton",
    "hodgkin",
    "hofstadter",
    "hoover",
    "hopper",
    "hugle",
    "hypatia",
    "ishizaka",
    "jackson",
    "jang",
    "jemison",
    "jennings",
    "jepsen",
    "johnson",
    "joliot",
    "jones",
    "kalam",
    "kapitsa",
    "kare",
    "karpathy",
    "keldysh",
    "keller",
    "kepler",
    "khayyam",
    "khorana",
    "kilby",
    "kirch",
    "knuth",
    "kowalevski",
    "lalande",
    "lamarr",
    "lamport",
    "leakey",
    "leavitt",
    "lecun",
    "lederberg",
    "lehmann",
    "lewin",
    "lichterman",
    "liskov",
    "lovelace",
    "lumiere",
    "mahavira",
    "margulis",
    "matsumoto",
    "maxwell",
    "mayer",
    "mccarthy",
    "mcclintock",
    "mclaren",
    "mclean",
    "mcnulty",
    "mendel",
    "mendeleev",
    "meitner",
    "meninsky",
    "merkle",
    "mestorf",
    "minsky",
    "mirzakhani",
    "montalcini",
    "moore",
    "morse",
    "murdock",
    "moser",
    "napier",
    "nash",
    "neumann",
    "newton",
    "nightingale",
    "nobel",
    "noether",
    "northcutt",
    "noyce",
    "panini",
    "pare",
    "pascal",
    "pasteur",
    "payne",
    "perlman",
    "pike",
    "poincare",
    "poitras",
    "proskuriakova",
    "ptolemy",
    "raman",
    "ramanujan",
    "ride",
    "ritchie",
    "rhodes",
    "robinson",
    "roentgen",
    "rosalind",
    "rubin",
    "saha",
    "sammet",
    "sanderson",
    "satoshi",
    "shamir",
    "shannon",
    "shaw",
    "shirley",
    "shockley",
    "shtern",
    "sinoussi",
    "snyder",
    "solomon",
    "spence",
    "stonebraker",
    "sutherland",
    "swanson",
    "swartz",
    "swirles",
    "taussig",
    "tereshkova",
    "tesla",
    "tharp",
    "thompson",
    "torvalds",
    "tu",
    "turing",
    "varahamihira",
    "vaughan",
    "villani",
    "visvesvaraya",
    "volhard",
    "wescoff",
    "wilbur",
    "wiles",
    "williams",
    "williamson",
    "wilson",
    "wing",
    "wozniak",
    "wright",
    "wu",
    "yalow",
    "yonath",
    "zhukovsky",
];

pub fn generate_name<R: Rng>(rng: &mut R) -> String {
    loop {
        let left = LEFT.choose(rng).unwrap();
        let right = RIGHT.choose(rng).unwrap();

        // Skip boring_wozniak per requirements
        if *left == "boring" && *right == "wozniak" {
            continue;
        }

        // Randomly choose between dot and hyphen
        let sep = if rng.gen_bool(0.5) { "." } else { "-" };

        // Generate a random number between 1 and 9999 (inclusive, up to 4 digits, not padded)
        let num = rng.gen_range(1..10000);

        let name = format!("{}{}{}{}{}", left, sep, right, sep, num);

        // Keep name within subdomain character limit of 32 characters
        if name.len() <= 32 {
            return name;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::web::alias_api::validate_alias;
    use rand::SeedableRng;
    use rand::rngs::SmallRng;

    #[test]
    fn test_generate_name_properties() {
        let mut rng = SmallRng::from_entropy();

        for _ in 0..1000 {
            let name = generate_name(&mut rng);

            // 1. Must not contain underscores
            assert!(
                !name.contains('_'),
                "Generated name should not contain underscores: {}",
                name
            );

            // 2. Length must be <= 32
            assert!(name.len() <= 32, "Generated name too long: {}", name);

            // 3. Must use the same separator consistently (either '.' or '-')
            let dot_count = name.chars().filter(|&c| c == '.').count();
            let hyphen_count = name.chars().filter(|&c| c == '-').count();

            assert!(
                (dot_count == 2 && hyphen_count == 0) || (dot_count == 0 && hyphen_count == 2),
                "Generated name must use either '.' or '-' consistently as the separator exactly twice: {}",
                name
            );

            // 4. Must end with a number of 1 to 4 digits
            let parts: Vec<&str> = if dot_count == 2 {
                name.split('.').collect()
            } else {
                name.split('-').collect()
            };

            assert_eq!(parts.len(), 3, "Name must be split into 3 parts: {}", name);
            let num_str = parts[2];
            assert!(
                !num_str.is_empty() && num_str.len() <= 4,
                "Number part must be 1 to 4 digits: {}",
                num_str
            );
            let num: u32 = num_str.parse().expect("Third part must be a valid number");
            assert!((1..=9999).contains(&num));

            // 5. Must not contain the boring wozniak combination
            assert!(
                !(parts[0] == "boring" && parts[1] == "wozniak"),
                "Should not generate boring wozniak combination: {}",
                name
            );

            // 6. Must pass the actual alias validation rules
            assert!(
                validate_alias(&name, false).is_ok(),
                "Generated name '{}' failed alias validation",
                name
            );
        }
    }
}
